server:
  port: 8082
spring:
  application:
    name: "reports"
  devtools:
    add-properties: false
  profiles:
    include: null
aws:
  dynamodb:
    region: "${AWS_REGION:us-east-1}"
    accessKey: "${AWS_ACCESS_KEY_ID}"
    secretKey: "${AWS_SECRET_ACCESS_KEY}"
    endpoint: "${AWS_DYNAMODB_ENDPOINT:https://dynamodb.us-east-1.amazonaws.com}"
springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"
routes:
  paths:
    reports: "/api/v1/reports"
security:
  jwt:
    keys-location:
      public: "${JWT_PUBLIC_KEY:classpath:keys/public_key.pem}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
entrypoint:
  sqs:
    region: "${MY_AWS_REGION:us-east-1}"
    approvedLoanQueueUrl: "${AWS_SQS_APPROVED_LOAN_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225422344476/loan-approved-queue}"
    waitTimeSeconds: "20"
    maxNumberOfMessages: "10"
    visibilityTimeoutSeconds: "10"
    numberOfThreads: "1"
