server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  application:
    name: "reports"
  devtools:
    add-properties: false

management:
  endpoints:
    web:
      base-path: ${SERVER_ACTUATOR_PATH}
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

aws:
  dynamodb:
    region: ${AWS_REGION}
  ses:
    region: ${AWS_REGION}
    sourceEmail: ${AWS_SES_SOURCE_EMAIL}
    destinationEmail: ${AWS_SES_DESTINATION_EMAIL}

springdoc:
  swagger-ui:
    path: "/report/api/doc/swagger-ui.html"
  api-docs:
    path: "/report/api/doc/api-docs"

routes:
  paths:
    reports: "/report/api/v1/reports"

security:
  jwt:
    keys:
      public: ${JWT_PUBLIC_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

entrypoint:
  sqs:
    region: ${AWS_REGION}
    approvedLoanQueueUrl: ${AWS_SQS_APPROVED_LOAN_QUEUE_URL}
    reportTaskQueueUrl: ${AWS_SQS_REPORT_TASK_QUEUE_URL}
    waitTimeSeconds: ${AWS_SQS_WAIT_TIME_SECONDS}
    maxNumberOfMessages: ${AWS_SQS_MAX_MESSAGES}
    visibilityTimeoutSeconds: ${AWS_SQS_VISIBILITY_TIMEOUT}
    numberOfThreads: ${AWS_SQS_THREADS}
